### ISSUE TITLE
关于 | 年少万兜鍪

### ISSUE THREAD

**Issue by Jinyu-M** [Jinyu-M/jinyu-m.github.io#5]
https://jinyu-m.github.io/post/about/ 

 
尘世恰好，有诗有酒刚好吐槽~

🏠 关于本站
这里大多是博主平时读论文时的一些笔记和理解，比较杂乱，还请谅解。
👨‍💻 博主是谁
博主是北京航空航天大学自动化科学与电气工程学院的一枚小硕，从事SLAM、Place Recogniti...

**Comment by yuukidach** [comment]
你好，我是BUAA的一枚本科生，看到博主的研究觉得很有意思。希望能看到更多。
